In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [3]:
df = pd.read_csv('heart_disease_data.csv')

In [4]:
df.head()

   age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
0   63    1   3       145   233    1  ...      0      2.3      0   0     1       1
1   37    1   2       130   250    0  ...      0      3.5      0   0     2       1
2   41    0   1       130   204    0  ...      0      1.4      2   0     2       1
3   56    1   1       120   236    0  ...      0      0.8      2   0     2       1
4   57    0   0       120   354    0  ...      1      0.6      2   0     2       1

[5 rows x 14 columns]

In [6]:
df.tail()

     age  sex  cp  trestbps  chol  fbs  ...  exang  oldpeak  slope  ca  thal  target
298   57    0   0       140   241    0  ...      1      0.2      1   0     3       0
299   45    1   3       110   264    0  ...      0      1.2      1   0     3       0
300   68    1   0       144   193    1  ...      0      3.4      1   2     3       0
301   57    1   0       130   131    0  ...      1      1.2      1   1     3       0
302   57    0   1       130   236    0  ...      0      0.0      1   1     2       0

[5 rows x 14 columns]

In [8]:
df.shape

(303, 14)

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       303 non-null    int64
 1   sex       303 non-null    int64
 2   cp        303 non-null    int64
 3   trestbps  303 non-null    int64
 4   chol      303 non-null    int64
 5   fbs       303 non-null    int64
 6   restecg   303 non-null    int64
 7   thalach   303 non-null    int64
 8   exang     303 non-null    int64
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64
 11  ca        303 non-null    int64
 12  thal      303 non-null    int64
 13  target    303 non-null    int64
dtypes: float64(1), int64(13)
memory usage: 33.3 KB

In [10]:
df.describe()

              age         sex          cp  ...          ca        thal      target
count  303.000000  303.000000  303.000000  ...  303.000000  303.000000  303.000000
mean    54.366337    0.683168    0.966997  ...    0.729373    2.313531    0.544554
std      9.082101    0.466011    1.032052  ...    1.022606    0.612277    0.498835
min     29.000000    0.000000    0.000000  ...    0.000000    0.000000    0.000000
25%     47.500000    0.000000    0.000000  ...    0.000000    2.000000    0.000000
50%     55.000000    1.000000    1.000000  ...    0.000000    2.000000    1.000000
75%     61.000000    1.000000    2.000000  ...    1.000000    3.000000    1.000000
max     77.000000    1.000000    3.000000  ...    4.000000    3.000000    1.000000

[8 rows x 14 columns]

In [11]:
df['target'].value_counts()

target
1    165
0    138
Name: count, dtype: int64

#1: Defective Heart
#0 : Healthy heart

In [12]:
X = df.drop(columns='target' ,axis=1)    #remove the target from the data

In [13]:
X

     age  sex  cp  trestbps  chol  ...  exang  oldpeak  slope  ca  thal
0     63    1   3       145   233  ...      0      2.3      0   0     1
1     37    1   2       130   250  ...      0      3.5      0   0     2
2     41    0   1       130   204  ...      0      1.4      2   0     2
3     56    1   1       120   236  ...      0      0.8      2   0     2
4     57    0   0       120   354  ...      1      0.6      2   0     2
..   ...  ...  ..       ...   ...  ...    ...      ...    ...  ..   ...
298   57    0   0       140   241  ...      1      0.2      1   0     3
299   45    1   3       110   264  ...      0      1.2      1   0     3
300   68    1   0       144   193  ...      0      3.4      1   2     3
301   57    1   0       130   131  ...      1      1.2      1   1     3
302   57    0   1       130   236  ...      0      0.0      1   1     2

[303 rows x 13 columns]

In [14]:
Y=df['target']

In [15]:
Y

0      1
1      1
2      1
3      1
4      1
      ..
298    0
299    0
300    0
301    0
302    0
Name: target, Length: 303, dtype: int64

SPLIT THE DATASET INTO TRAIN TEST DATA

In [16]:
X_train , X_Test , Y_train , Y_test = train_test_split(X,Y,test_size=0.2,stratify=Y,random_state=23)

In [17]:
print(X_train.shape,X_Test.shape)

(242, 13) (61, 13)

**MODEL TRAINING**

In [18]:
model = LogisticRegression()

In [19]:
#Train the model with training data
model.fit(X_train , Y_train)

/usr/local/lib/python3.13/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [21]:
Y_pred = model.predict(X_Test)

In [22]:
Y_train

61     1
83     1
103    1
160    1
119    1
      ..
251    0
167    0
201    0
281    0
79     1
Name: target, Length: 242, dtype: int64

In [24]:
score = accuracy_score(Y_test,Y_pred)

In [25]:
print ("the accuracy score is ", score )

the accuracy score is  0.8524590163934426

**BUILDING A PREDICTIVE SYSTEM**

In [26]:
input_data = (62,0,0,140,268,0,0,160,0,3.6,0,2,2)
#change the input_data into array

arr = np.array(input_data)

In [27]:
print(arr)

[ 62.    0.    0.  140.  268.    0.    0.  160.    0.    3.6   0.    2.
   2. ]

In [29]:
prediction= model.predict(arr.reshape(1,-1))

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [30]:
print(prediction)

[0]

In [32]:
if prediction == 0:
  print('You are Healthy')
else:
  print("Consult your doctor")

You are Healthy

### Exporting the Trained Model

In [33]:
import pickle

# Save the model to disk
filename = 'heart_disease_model.sav'
pickle.dump(model, open(filename, 'wb'))
print(f"Model saved successfully as '{filename}'!")

Model saved successfully as 'heart_disease_model.sav'!

To verify that the model was exported properly, let's load it back and check if we can make a prediction with it.

In [34]:
# Load the model from disk
loaded_model = pickle.load(open(filename, 'rb'))

# Test a prediction with the loaded model
test_prediction = loaded_model.predict(arr.reshape(1, -1))
print("Loaded model test prediction:", test_prediction)

Loaded model test prediction: [0]

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

In [36]:
import pickle
import numpy as np

# 1. Load the exported model
loaded_model = pickle.load(open('heart_disease_model.sav', 'rb'))

# 2. Define a new person's data for prediction
# Format: (age, sex, cp, trestbps, chol, fbs, restecg, thalach, exang, oldpeak, slope, ca, thal)
new_input_data = (45, 1, 3, 110, 264, 0, 1, 132, 0, 1.2, 1, 0, 3)

# Convert to numpy array and reshape for prediction (1 sample, 13 features)
query_features = np.array(new_input_data).reshape(1, -1)

# 3. Make the prediction
new_prediction = loaded_model.predict(query_features)

print("Predicted class:", new_prediction[0])
if new_prediction[0] == 0:
  print('Healthy heart')
else:
  print('Defective heart (Consult your doctor)')

Predicted class: 1
Defective heart (Consult your doctor)

/usr/local/lib/python3.13/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(